dbdata:
  image: davidpthomas/radar-postgres:1.0.0
  volumes:
    - /var/lib/postgresql
  command: /bin/true

postgres:
  image: davidpthomas/radar-postgres:1.0.0
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"

redis:
  image: davidpthomas/radar-redis

web:
  build: .
  ports:
    - "3000:3000"
  command: bundle exec rails server --port=3000 --binding='0.0.0.0'
  volumes:
    - .:/apps/radar-webapp
  links:
    - redis
    - postgres

