# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 111b1f2e9f45a2077521c1a6f8c22e3137b322270653ffd899a1a58fb3065d1dfe7802cb4970bd2411f3f6aee580756d77e12ff743855ca392cb596c6275db07

test:
  secret_key_base: 5d67704c2e83bea1d211c4236e93d065ccd89e6c4ba92a26f18723f6beef1c1acba498359043ecc7347cd4b0471dd7fb93e553c07b2e745fa0f9b2021e898c9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
